// Code generated by go generate; DO NOT EDIT.

package models

func (s *ListMetrics) Reset() {
	s.List = nil

}

func (s *Metrics) Reset() {
	s.ID = ""
	s.MType = ""
	s.Delta = nil
	s.Value = nil
	s.Hash = ""

}

func (s *Data) Reset() {
	s.TS = 0
	s.MetricNames = nil
	s.IP = ""

}

func (s *DataList) Reset() {
	s.Events = nil

}
