// Code generated by go generate; DO NOT EDIT.

package service

func (s *ServerComponents) Reset() {
	s.server = nil
	s.store = nil
	s.logger = nil
	s.dbConn = nil

}

func (s *PeriodicSaver) Reset() {
	s.store = nil
	s.interval = 0
	s.filePath = ""
	s.logger = nil
	s.stopCh = nil
	s.done = nil

}
