// Code generated by go generate; DO NOT EDIT.

package config

func (s *Config) Reset() {
	s.Addr = ""
	s.StoreInterval = 0
	s.FileStorage = ""
	s.Restore = false
	s.AddrDB = ""
	s.Key = ""
	s.AuditFile = ""
	s.AuditURL = ""

}
